### ISSUE TITLE
How to use it on docker ?

### ISSUE THREAD

**Issue by JeromeVi** [pmsipilot/docker-compose-viz#11]
Hi,
I don't understand how to use it with the Docker command. Could you explain it a little bit more ?

**Comment by bperel** [comment]
You can just run the following command, considering that your current directory is where your docker-compose.yml is located:
`docker run --rm -it --name dcv -v $(pwd):/input pmsipilot/docker-compose-viz render docker-compose.yml`

It will generate docker-compose.png in that directory.

**Comment by JeromeVi** [comment]
@bperel thank you for the answer :)
