### ISSUE TITLE
Read multiple yml files

### ISSUE THREAD

**Issue by smgladkovskiy** [pmsipilot/docker-compose-viz#18]
Or, as alternative, read .env and search COMPOSE_FILE var to read all yml configs for projects.

We divide all infrastructure of project to separated services. So, we have .env, where we write all ymls that are needed to start the project.
For example: `COMPOSE_FILE=docker-compose.yaml:docker-compose.legacy.yaml:docker-compose.env.yaml`

Here it in docker-compose refs: https://docs.docker.com/compose/reference/envvars/#compose_file

**Comment by jubianchi** [comment]
Hi @smgladkovskiy!

Would you mind trying pmsipilot/docker-compose-viz#17? It's a first implementation to support multiple `yml` files. It actually only reads the override file but we have to make sure that the merging logic is correct.

Once we are OK on the merging rules to apply, I will be very easy to implement your feature request.

**Comment by rdpravin1895** [comment]
Hi @jubianchi , has this been done? Is there any documentation on how to read multiple compose yml files?
