### ISSUE TITLE
/dcv/bin/entry_script.sh: line 12: Warning:: not found

### ISSUE THREAD

**Issue by AyushyaChitransh** [pmsipilot/docker-compose-viz#20]
I ran the command `docker run --rm -it --name dcv -v $(pwd):/input pmsipilot/docker-compose-viz render -m image docker-compose.yml` in the directory that contained the docker project along with  `docker-compose.yml`. But got this error.

> /dcv/bin/entry_script.sh: line 12: Warning:: not found

I have installed PHP7.1 and composer locally, is there any configuration that I need to make to get this working?

**Comment by AyushyaChitransh** [comment]
Okay, I realized just now that using `docker run` and using `PHP` and `composer` were two separate ways.

I was able to generate the required diagram using PHP and composer, but the issue with docker still remains.

**Comment by jubianchi** [comment]
Hi @AyushyaChitransh!

Thanks for reporting this issue.

Unfortunately, I can't reproduce your bug. I tried the following:

* Pulling the `latest` image from the Docker registry and running your command,
* Locally building the image from `master` and running your command.

None of the two produced the behavior you describe. Could you please provide more information on how you got this? Did you build the image yourself, if yes, how did you do that? Did you use the one from the registry, if yes, from which branch/commit?

Thanks!

**Comment by AyushyaChitransh** [comment]
I tried both, building image myself and also pulling the image from the repository. And both cases I got the same result.

To ensure the latest image, I tried the following:

- Running `docker images` to ensure that I am not using any pre-built image.

- Running `docker ps -a` to ensure that there is no previous container.

- `cd` to the directory containing `docker-compose.yml` 

- Running `docker run --rm -it --name dcv -v $(pwd):/input pmsipilot/docker-compose-viz render -m image docker-compose.yml`

The error I got was the same. After that I built image locally by following these steps:

- Cloned this repo

- `cd` to its directory

- Running `make vendor` because when I tried previously, it failed and said something about `vendor`

- Running `docker build .` successfully generated the image.

But the new image gave same error. 

I also tried to see if there is anything wrong with the entrypoint, but that seemed correct. I ran these commands in another directory which had docker-compose.yml file: 

`docker run --rm -it --name dcv -v $(pwd):/input pmsipilot/docker-compose-viz render render -m image docker-compose.yml` and it results in

> Too many arguments, expected arguments "command" "input-file".

**Comment by jubianchi** [comment]
@AyushyaChitransh I figured out what the problem is: something changed in the base image (`php:7.1-alpine`) so I had to change the entrypoint a bit to avoid the bug.

#21 has been opened with the fix, could you please test and confirm it works?

You can use the following command to test against the image published from the PR branch:

```sh
docker run --rm -it --name dcv -v $(pwd):/input pmsipilot/docker-compose-viz:fix-entrypoint render -m image docker-compose.yml
```
