### ISSUE TITLE
App (both Docker and native flavour) doesn't work, PHP error

### ISSUE THREAD

**Issue by Braintelligence** [pmsipilot/docker-compose-viz#22]
When executing your command as stated in the README I get this error:

```
Fatal error: Uncaught TypeError: Argument 2 passed to PMSIpilot\DockerComposeViz\addService() must be of the type string, array given, called in /dcv/src/functions.php on line 262 and defined in /dcv/src/functions.php:338
Stack trace:
#0 /dcv/src/functions.php(262): PMSIpilot\DockerComposeViz\addService(Object(Fhaculty\Graph\Graph), Array)
#1 /dcv/src/functions.php(92): PMSIpilot\DockerComposeViz\makeVerticesAndEdges(Object(Fhaculty\Graph\Graph), Array, Array, Array, true, 'docker-compose....')
#2 /dcv/src/application.php(81): PMSIpilot\DockerComposeViz\createGraph(Array, Array, Array, true, 'docker-compose....')
#3 [internal function]: Closure->PMSIpilot\DockerComposeViz\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /dcv/vendor/symfony/console/Command/Command.php(262): call_user_func(Object(Closure), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /dcv/vendor/symfony/console/Application. in /dcv/src/functions.php on line 338
```

**Comment by Braintelligence** [comment]
And the same happens when trying to run via dcv...

**Comment by jubianchi** [comment]
Please, can you provide the `docker-compose.yml` you are using ?

**Comment by jubianchi** [comment]
@Braintelligence are you using something like this:

```yaml
version: '2.1'
services:
  web:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
```

**Comment by Braintelligence** [comment]
I'm using it on this:

https://github.com/mailcow/mailcow-dockerized/blob/master/docker-compose.yml

**Comment by jubianchi** [comment]
@Braintelligence Ok fine, thanks for your feedback. A PR is coming ;)

**Comment by Braintelligence** [comment]
Thank you! I'd love to create an image 😸.
Really don't want to push you, but it would be totally friggin' awesome, if this would work until 21. November. I wanted to use the graphics in my thesis 😸.

**Comment by jubianchi** [comment]
@Braintelligence an image was automatically pushed to the docker registry from the PR.

It's available here: `pmsipilot/docker-compose-viz:conditions-depends-on`. Please test it and report any issues ;)

**Comment by Braintelligence** [comment]
Awesome! It worked!
Oh my god, such a huge image 😸.
Is there somehow a way to tell the app to create an image with a ratio that prefers height over width? 😸

**Comment by jubianchi** [comment]
@Braintelligence with your `docker-compose.yml` the result seems better if you use the `--horizontal` option:

![image](https://user-images.githubusercontent.com/327237/32922268-b1f01ee0-cb31-11e7-94f6-f0b8905e78d0.png)

**Comment by Braintelligence** [comment]
Ahh I see!
Awesome!

I looked for an app like this for hours and yours seemed to produce the image with the most visualized info. I'm glad this works now 😸.

**Comment by jubianchi** [comment]
@Braintelligence I'm happy this is what you was searching for. Fell free to to report any other issue you may encounter.

I'm closing this one for now.

Thanks again!
