### ISSUE TITLE
Failure on override

### ISSUE THREAD

**Issue by lrkwz** [pmsipilot/docker-compose-viz#28]
Suppose you have `docker-compose.yml`

    version: '3'
    services:
      web:
        image: 'nginx'
        ports:
        - 80
        links:
        - db
      db:
        image: mysql

and `docker-compose.override.yml`:

    version: '3'
    services:
      sonarqube:
        image: 'sonarqube'
        links:
        - db

the output is: 

![image](https://user-images.githubusercontent.com/1025560/35046750-2e94dfb2-fb98-11e7-9d38-6bbc714e1530.png)

File are correct since `docker-compose config` output is 

    services:
      db:
        image: mysql
      sonarqube:
        image: sonarqube
        links:
        - db
      web:
        image: nginx
        links:
        - db
        ports:
        - 80/tcp
    version: '3.0'

BTW if you copy `docker-compose config`'s output in a new 'docker-compose.yml` the image is rendered correctly 

![image](https://user-images.githubusercontent.com/1025560/35046990-e3a0e9be-fb98-11e7-8616-da1debbaac09.png)

**Comment by jubianchi** [comment]
Hi @lrkwz!

Thanks for reporting this issue.

It has been fixed. It was caused by the logic we use to merge configurations. It should be OK now. I also added a check on version: if there is a mismatch between the main file and the override, `dcv` will raise an exception.
