### ISSUE TITLE
failed to open stream: Permission denied

### ISSUE THREAD

**Issue by rvernica** [pmsipilot/docker-compose-viz#41]
I got the latest Docker image from Docker Hub:
```bash
> docker run --rm -it --name dcv -v $(pwd):/input:rw pmsipilot/docker-compose-viz
Warning: file_put_contents(/input/docker-compose.png): failed to open stream: Permission denied in /dcv/src/application.php on line 137
```
I copied the `docker-compose.yml` to `/tmp` did `chmod a+r` on it, and ran the `docker run` command there. It worked fine.

This is due to specifying the `dcv` username in [`Dockerfile`](https://github.com/pmsipilot/docker-compose-viz/blob/ec09768b7eea7fad39339dac18e938a347e9fdaa/Dockerfile#L18). It is easy to fix by not imposing a username and having the `root` user being used.

This issue was mentioned before in #21, but as part of a separate thread.

**Comment by markiewb** [comment]
I also had to create a subfolder to get it working

```
mkdir output && chmod 777 output
docker run --rm -it --network none -v $(pwd):/input:rw pmsipilot/docker-compose-viz render -m image --output-file output/docker-compose.yml.png docker-compose.yml 
```

**Comment by thamerbelfkihthamer** [comment]
there is no one able to resolve this issue?

**Comment by markiewb** [comment]
@thamerbelfkihthamer Have you tried my approach above? It had worked for me this way...

**Comment by pengyuan-zhou** [comment]
> docker run --rm -it --network none -v $(pwd):/input:rw pmsipilot/docker-compose-viz render -m image --output-file output/docker-compose.yml.png docker-compose.yml

works like a charm

**Comment by jubianchi** [comment]
Hi everyone here! 👋🏻

I just added the "help wanted" label: if anyone wants to contribute something in the README, like a "Caveats" paragraph explaining this kind of problems and how to solve them it would be really apreciated.

I can't actually reproduce the problem (I'm working on MacOS with Docker For Mac) and never had any problem so I don't think I will be able to provide the best solution here.

Thank you all 🙏

**Comment by pengyuan-zhou** [comment]
> Hi everyone here! 👋🏻
> 
> I just added the "help wanted" label: if anyone wants to contribute something in the README, like a "Caveats" paragraph explaining this kind of problems and how to solve them it would be really apreciated.
> 
> I can't actually reproduce the problem (I'm working on MacOS with Docker For Mac) and never had any problem so I don't think I will be able to provide the best solution here.
> 
> Thank you all 🙏

Hi, I met this today on ubuntu 16.04, no specific reason noticed, and I just used the command suggested by @markiewb then solved. If helpful, I can add this into README, or better, if @markiewb would.

**Comment by markiewb** [comment]
Proposed as MR #51

**Comment by jubianchi** [comment]
Thanks @pengyuan-zhou for confirming @markiewb solution.

The MR has been merged.
