### ISSUE TITLE
file_put_contents Permission denied

### ISSUE THREAD

**Issue by thorus90** [pmsipilot/docker-compose-viz#42]
I followed the instructions in the readme to install docker-compose-viz, but while running
```
docker run --rm -it --name dcv -v $(pwd):/input pmsipilot/docker-compose-viz render -m image docker-compose.yml
```
I get the error:
```
Warning: file_put_contents(/input/docker-compose.png): failed to open stream: Permission denied in /dcv/src/application.php on line 137
```
What could be the problem?

**Comment by themanifold** [comment]
Looks like you might be running the script in a directory where you don't
have write access.

**Comment by thorus90** [comment]
I'm running this as root, I also tried to create the directory input in the directory my docker-compose.yml is before running, but this did not help

**Comment by thorus90** [comment]
Thank you @luksurious . This works for me.
