### ISSUE TITLE
Render SVGs?

### ISSUE THREAD

**Issue by Ocramius** [pmsipilot/docker-compose-viz#52]
Hey there, I was wondering if this project can also render SVGs?

The reason is that I want to add it as a CI entry that auto-commits the repository structure on regular basis, but that means committing multiple kilobytes of blob if I were to generate PNGs all the time, whereas an SVG image is much more efficient.

If the tool uses `dot` (graphviz) internally, `-Tsvg` should suffice, and I can try sending a patch if pointed at the right place and this is a welcome addition.

Or should I use `dot` as format, and then render the image myself?

**Comment by jubianchi** [comment]
Hi @Ocramius! Glad to see you here :)

Indeed this would be very nice! It seems the underlying library can do that: https://github.com/graphp/graphviz/blob/master/src/GraphViz.php

I can look into it today if you want, it should not take long.

**Comment by jubianchi** [comment]
@Ocramius PR ready, let me know if it's OK for you, on such case I'll :shipit:
